// <auto-generated />

using GenericBlazorWebApi.Tests.Shared.TestData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tests.Migrations
{
    [DbContext(typeof(TestDataContext))]
    [Migration("20220903154650_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Tests.TestModels.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nullable")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestModel1",
                            Nullable = "",
                            UniqueName = "TestModel1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TestModel2",
                            Nullable = "",
                            UniqueName = "TestModel2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TestModel3",
                            Nullable = "",
                            UniqueName = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
